
import React, { useState } from 'react';

const OSHelper: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'basics' | 'logic' | 'stream' | 'glossary' | 'faq'>('basics');
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  const glossary = [
    { term: 'Neural Link', def: 'The primary encrypted connection between the explorer’s consciousness and the OS core. Stability is measured in "Synaptic MHz".' },
    { term: 'Knowledge Node', def: 'A multidimensional curriculum module. Each node consists of 12 sequential Synaptic Layers of increasing complexity.' },
    { term: 'Archive Mode', def: 'A state of operational redundancy. When external neural APIs are unreachable, the OS serves local, pre-cached knowledge assets.' },
    { term: 'Synaptic Pulse', def: 'The clock speed of the user interface. Adjusting this in Settings changes the frequency of visual data-flow animations.' },
    { term: 'Credits (CRD)', def: 'Non-volatile system currency. CRD is minted upon the successful verification of knowledge and used for terminal equipment.' },
    { term: 'Mastery Phase', def: 'A tier-based ranking system. High-level Mastery Phases unlock advanced system software and higher-rarity artifacts.' },
    { term: 'Neural Desync', def: 'A catastrophic failure in the data stream, often caused by high latency. Requires manual Core Logic Verification to resolve.' },
    { term: 'Reflector Node', def: 'The emotional monitoring system. It parses user sentiment to adjust the "friction" of upcoming learning assessments.' },
    { term: 'Dopamine Priming', def: 'A mechanic used in the Behavior Gaming module to encourage consistent engagement through variable reward schedules.' }
  ];

  const faqs = [
    { 
      q: "How do I initialize a Knowledge Node?", 
      a: "Navigate to the Knowledge Ecosystem (App Manager). Select an available Node and click 'Initialize'. You must be at the required Level to begin certain high-tier nodes." 
    },
    { 
      q: "What are XP Multipliers and how do I get them?", 
      a: "Multipliers are generated by equipping gear in the Armory. For example, the 'Logic Core' provides a x1.1 boost. These stack with streak bonuses." 
    },
    { 
      q: "Why is my AI Stream showing an 'Interruption' error?", 
      a: "This occurs when the Neural Link exceeds 3000ms latency. Use the Neural Stream app to 'Verify Core Logic' or switch to Archive Mode for a static experience." 
    },
    { 
      q: "Can I create my own Knowledge Nodes?", 
      a: "Yes. Utilize the 'Tutor Hub' app to define parameters. Once deployed, the Mechdyane Core will generate a full 12-layer curriculum based on your objectives." 
    },
    { 
      q: "What happens if I break my Neural Streak?", 
      a: "Failing to link within a 24-hour cycle results in a streak reset. This lowers your passive XP gain and may lock certain 'Legendary' achievements." 
    }
  ];

  const sections = {
    basics: (
      <div className="space-y-8 animate-in fade-in duration-500">
        <div className="bg-blue-600/10 border border-blue-500/20 p-8 rounded-[2rem] space-y-4 relative overflow-hidden">
           <div className="absolute top-0 right-0 p-4 opacity-10">
              <i className="fas fa-microchip text-8xl"></i>
           </div>
           <h3 className="text-xl font-black text-white font-orbitron uppercase tracking-tighter">OS Lineage & Purpose</h3>
           <p className="text-sm text-slate-300 leading-relaxed font-medium">
             Mechdyane OS (v9.1) is not a browser; it is a <strong>Neural Environment</strong>. Built to combat "The Great Distraction," Mechdyane utilizes Gamified OS Dynamics to force the human brain into states of deep, sequential growth.
           </p>
           <div className="pt-4 flex gap-4">
              <div className="px-4 py-2 bg-blue-600/20 rounded-xl border border-blue-500/30">
                 <p className="text-[8px] font-black text-blue-400 uppercase tracking-widest">Core Engine</p>
                 <p className="text-[10px] font-bold text-white">Gemini-3-Flash</p>
              </div>
              <div className="px-4 py-2 bg-emerald-600/20 rounded-xl border border-emerald-500/30">
                 <p className="text-[8px] font-black text-emerald-400 uppercase tracking-widest">Logic Type</p>
                 <p className="text-[10px] font-bold text-white">Heuristic Adaptive</p>
              </div>
           </div>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
           <div className="glass p-8 rounded-[2rem] border-white/5 space-y-3 group hover:border-blue-500/20 transition-all">
              <i className="fas fa-shield-halved text-blue-500 text-2xl mb-2"></i>
              <h4 className="text-sm font-black text-white uppercase tracking-widest font-orbitron">The Mechanics</h4>
              <p className="text-xs text-slate-500 leading-relaxed">The "Rules" of the OS. XP, levels, and prerequisites. These provide the skeleton for your growth journey.</p>
           </div>
           <div className="glass p-8 rounded-[2rem] border-white/5 space-y-3 group hover:border-emerald-500/20 transition-all">
              <i className="fas fa-wind text-emerald-500 text-2xl mb-2"></i>
              <h4 className="text-sm font-black text-white uppercase tracking-widest font-orbitron">The Dynamics</h4>
              <p className="text-xs text-slate-500 leading-relaxed">The "Interactions." How modules generate content, how gear affects stats, and how the OS reacts to your speed.</p>
           </div>
        </div>
      </div>
    ),
    logic: (
      <div className="space-y-8 animate-in fade-in duration-500">
        <h3 className="text-xl font-black text-white font-orbitron uppercase tracking-tighter">Growth Mechanics Matrix</h3>
        <div className="grid grid-cols-1 gap-4">
           {[
             { title: 'Level Progression', icon: 'fa-arrow-up-right-dots', desc: 'XP thresholds increase by 20% per level. Total mastery requires consistent verification.' },
             { title: 'Itemization', icon: 'fa-box-open', desc: 'Artifacts are not cosmetic. They are functional logic gates that modify your reward vectors.' },
             { title: 'Verification Gate', icon: 'fa-key', desc: 'You cannot bypass a node without achieving 80% accuracy in the Synaptic Layer assessment.' }
           ].map((m, i) => (
             <div key={i} className="flex gap-6 p-6 rounded-3xl bg-white/5 border border-white/5 group hover:bg-white/[0.08] transition-all">
               <div className="w-12 h-12 rounded-2xl bg-blue-600/20 text-blue-400 flex items-center justify-center shrink-0 border border-blue-500/20">
                  <i className={`fas ${m.icon}`}></i>
               </div>
               <div>
                  <p className="text-sm font-black text-white uppercase tracking-tight font-orbitron">{m.title}</p>
                  <p className="text-xs text-slate-400 mt-1 leading-relaxed">{m.desc}</p>
               </div>
             </div>
           ))}
        </div>
      </div>
    ),
    stream: (
      <div className="space-y-8 animate-in fade-in duration-500">
        <h3 className="text-xl font-black text-white font-orbitron uppercase tracking-tighter">The Synaptic Architecture</h3>
        <div className="bg-slate-900 border border-blue-500/20 p-10 rounded-[2.5rem] relative overflow-hidden">
           <div className="absolute inset-0 os-grid opacity-5"></div>
           <div className="relative z-10 space-y-6">
              <div className="flex items-center gap-4">
                 <div className="w-3 h-3 rounded-full bg-blue-500 animate-pulse"></div>
                 <p className="text-xs font-black text-blue-400 uppercase tracking-widest font-orbitron">Layer-0: Neural Interface</p>
              </div>
              <p className="text-sm text-slate-300 leading-relaxed font-medium pl-7 border-l border-blue-500/20">
                Mechdyane uses a <strong>Modular Heuristic Engine</strong>. When you launch a module, the OS creates a temporary Synaptic Buffer. It then pulls from the Gemini-3 Knowledge Base to "hydrate" the node with fresh, non-repetitive content.
              </p>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pl-7">
                 <div className="space-y-2">
                    <p className="text-[10px] font-black text-slate-500 uppercase tracking-widest">Primary Stream</p>
                    <div className="bg-blue-600/20 h-1 w-full rounded-full overflow-hidden">
                       <div className="h-full bg-blue-500 w-[90%]"></div>
                    </div>
                    <p className="text-[8px] text-slate-600 uppercase">Real-time Synthesis</p>
                 </div>
                 <div className="space-y-2">
                    <p className="text-[10px] font-black text-slate-500 uppercase tracking-widest">Static Archive</p>
                    <div className="bg-amber-600/20 h-1 w-full rounded-full overflow-hidden">
                       <div className="h-full bg-amber-500 w-[40%]"></div>
                    </div>
                    <p className="text-[8px] text-slate-600 uppercase">Local Recovery</p>
                 </div>
              </div>
           </div>
        </div>
      </div>
    ),
    glossary: (
      <div className="space-y-8 animate-in fade-in duration-500">
        <h3 className="text-xl font-black text-white font-orbitron uppercase tracking-tighter text-center">Comprehensive Terminology</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
           {glossary.map((item, i) => (
             <div key={i} className="glass p-8 rounded-[2rem] border-white/5 group hover:border-blue-500/30 transition-colors">
                <p className="text-[10px] font-black text-blue-400 uppercase tracking-[0.2em] mb-3 font-orbitron flex items-center gap-2">
                   <div className="w-1.5 h-1.5 rounded-full bg-blue-500/40"></div>
                   {item.term}
                </p>
                <p className="text-xs text-slate-400 leading-relaxed font-medium">{item.def}</p>
             </div>
           ))}
        </div>
      </div>
    ),
    faq: (
      <div className="space-y-8 animate-in fade-in duration-500">
        <h3 className="text-xl font-black text-white font-orbitron uppercase tracking-tighter text-center">Synaptic FAQ</h3>
        <div className="max-w-3xl mx-auto space-y-4">
          {faqs.map((faq, i) => (
            <div key={i} className="bg-slate-900/40 border border-white/5 rounded-3xl overflow-hidden transition-all">
              <button 
                onClick={() => setOpenFaq(openFaq === i ? null : i)}
                className="w-full px-8 py-5 flex items-center justify-between group hover:bg-white/5 transition-colors"
              >
                <span className={`text-xs font-black uppercase tracking-widest text-left ${openFaq === i ? 'text-blue-400' : 'text-slate-300'}`}>{faq.q}</span>
                <i className={`fas fa-chevron-${openFaq === i ? 'up' : 'down'} text-[10px] text-slate-600 transition-transform`}></i>
              </button>
              {openFaq === i && (
                <div className="px-8 pb-6 animate-in slide-in-from-top-2 duration-300">
                   <p className="text-xs text-slate-500 leading-relaxed font-medium border-t border-white/5 pt-4 italic">
                      {faq.a}
                   </p>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    )
  };

  return (
    <div className="p-6 md:p-12 space-y-12 h-full bg-[#020617]/40 overflow-y-auto custom-scrollbar pb-32 relative">
      <div className="absolute inset-0 os-grid opacity-5 pointer-events-none"></div>

      <header className="flex flex-col md:flex-row md:items-end justify-between gap-6 border-b border-white/5 pb-8 relative z-10">
        <div>
          <div className="flex items-center gap-3 mb-2">
            <span className="text-[10px] bg-blue-500/10 text-blue-400 px-3 py-1 rounded-full border border-blue-500/20 font-black tracking-widest animate-pulse">SYSTEM MANUAL</span>
          </div>
          <h1 className="text-3xl md:text-4xl font-black text-white uppercase tracking-tight font-orbitron">Mechdyane Operating Guide</h1>
          <p className="text-slate-500 font-medium text-xs uppercase tracking-[0.3em] mt-2">Field Manual for Neural Link v9.1.x</p>
        </div>
        <div className="w-14 h-14 rounded-2xl bg-blue-600/10 border border-blue-500/30 flex items-center justify-center text-blue-400 shadow-2xl shadow-blue-500/10 group">
           <i className="fas fa-book-open group-hover:scale-110 transition-transform"></i>
        </div>
      </header>

      {/* TABS NAVIGATION */}
      <div className="flex flex-wrap gap-2 md:gap-4 justify-center md:justify-start relative z-10">
        {[
          { id: 'basics', label: 'Basics', icon: 'fa-house-signal' },
          { id: 'logic', label: 'Mechanics', icon: 'fa-microchip' },
          { id: 'stream', label: 'Dynamics', icon: 'fa-bolt' },
          { id: 'glossary', label: 'Glossary', icon: 'fa-list' },
          { id: 'faq', label: 'FAQ', icon: 'fa-question-circle' }
        ].map(tab => (
          <button 
            key={tab.id}
            onClick={() => setActiveTab(tab.id as any)}
            className={`px-8 py-3.5 rounded-2xl text-[10px] font-black uppercase tracking-widest transition-all border flex items-center gap-3 font-orbitron ${activeTab === tab.id ? 'bg-blue-600 border-blue-600 text-white shadow-xl shadow-blue-500/30' : 'bg-white/5 border-white/5 text-slate-500 hover:text-slate-300 hover:bg-white/[0.03]'}`}
          >
            <i className={`fas ${tab.icon} text-xs`}></i>
            {tab.label}
          </button>
        ))}
      </div>

      <div className="max-w-4xl mx-auto py-4 relative z-10">
        {sections[activeTab]}
      </div>

      <footer className="pt-24 text-center space-y-6 opacity-30 group hover:opacity-60 transition-opacity relative z-10">
         <div className="flex items-center justify-center gap-8">
            <div className="h-px w-24 bg-slate-800"></div>
            <p className="text-[10px] font-black text-slate-500 uppercase tracking-[0.5em] font-orbitron">Neural Node Certification STB-09</p>
            <div className="h-px w-24 bg-slate-800"></div>
         </div>
         <div className="space-y-1">
            <p className="text-[8px] text-slate-600 font-bold uppercase tracking-widest">Mechdyane Cognitive Systems © 2025</p>
            <p className="text-[7px] text-slate-700 font-black uppercase tracking-[0.2em]">Restricted Field Manual • Authorized Explorers Only</p>
         </div>
      </footer>
    </div>
  );
};

export default OSHelper;
